server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: api-gateway
    gateway:
      locator:
        enabled: true
        lowerCaseServiceId: true
        filters:
          - PreserveHostHeader
      routes: # 路由数组（路由就是请求满足什么条件的时候转到哪个微服务）
        - id: user_route # 路由唯一性标识
          uri: http://127.0.0.1:8101 # 路由转发到的地址
          predicates: # 断言（路由转发要满足的条件）
            - Path=/oneapp/** # 当请求路径满足Path指定的规则时，才进行路由转发
#            - After=2021-03-01T00:00:00.000+08:00[Asia/Shanghai]
#            - Before=2021-03-31T23:59:59.000+08:00[Asia/Shanghai]
#            - Between=2021-03-01T00:00:00.000+08:00[Asia/Shanghai], 2021-03-31T23:59:59.000+08:00[Asia/Shanghai]
#            - Method=GET
#            - Query=userid, 0
#            - Userid=0,2 # =左边的Userid和UseridRoutePredictFactory.java开头的Userid保持一致
          filters: # 过滤器，请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉一层路径
        - id: ticket_route
          uri: http://localhost:8102
          predicates:
            - Path=/ticket/**
          filters:
            - StripPrefix=1
        - id: user_lb
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/oneapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

management:
  endpoints:
    web:
      exposure:
        include: "*"
